#pragma once
#include <omega/platform.h>

#define OMG_DEBUG 1
#define OMG_ENTRY 1

#define OMG_SUPPORT_WIN 1
#define OMG_WINAPI_DYNAMIC 1
#define OMG_WINAPI_DYNAMIC_UGLY 1
#define OMG_WINAPI_DYNAMIC_COMPAT 1

#define OMG_LOG_MIN_LEVEL OMG_LOG_CATEGORY_INFO
#define OMG_LOG_OMG_MIN_LEVEL OMG_LOG_CATEGORY_INFO

#define OMG_IMPL_STD_FUNCS !OMG_HAS_STD // TODO
